# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping-pong.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fping-pong.proto\x12\x11\x63om.training.grpc\"1\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"2\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\x61\n\x0fPingPongService\x12N\n\x0bgetPingPong\x12\x1e.com.training.grpc.PingRequest\x1a\x1f.com.training.grpc.PongResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pong_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=38
  _PINGREQUEST._serialized_end=87
  _PONGRESPONSE._serialized_start=89
  _PONGRESPONSE._serialized_end=139
  _PINGPONGSERVICE._serialized_start=141
  _PINGPONGSERVICE._serialized_end=238
# @@protoc_insertion_point(module_scope)
